# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 179162fe642d216cdb20e6102651f1bf33bebe4f0b6ff4cd0fdd30d129302a737a95688aeb183de344dec935d7e213bb49721c55c5682e28c630404cab72e449

test:
  secret_key_base: 077bef9d5c3c532bd70d58012bf69233f94149132e8dcd027cf41090115122f5af6b4c04568668e0f0e0960e6a63643dfd8f5fb8283e8e6bd37623eafe3d5c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
